# Generated by Django 3.2.7 on 2022-02-01 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], max_length=100, null=True)),
                ('ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': ' Players',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('PLAYING', 'PLAYING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='SCHEDULED', max_length=50, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('match_result', models.CharField(blank=True, choices=[('WIN', 'WIN'), ('DRAW', 'DRAW')], max_length=100, null=True)),
                ('player_one_entry_ranking', models.IntegerField(blank=True, null=True)),
                ('player_two_entry_ranking', models.IntegerField(blank=True, null=True)),
                ('player_one_ranking_change', models.IntegerField(blank=True, null=True)),
                ('player_two_ranking_change', models.IntegerField(blank=True, null=True)),
                ('player_one_points_change', models.IntegerField(blank=True, null=True)),
                ('player_two_points_change', models.IntegerField(blank=True, null=True)),
                ('follow_live', models.CharField(blank=True, default='https://<LINK TO BE COMPLETED>', max_length=255, null=True)),
                ('player_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to='ChessAdminApp.player')),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='ChessAdminApp.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ChessAdminApp.player')),
            ],
        ),
    ]
